// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("postgres")
	ScopeName = "github.com/wabb-in/postgresexporter"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
	LogsStability    = component.StabilityLevelDevelopment
	TracesStability  = component.StabilityLevelDevelopment
)
